config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  
  get "/admin" => "admin/users#index" # 管理者画面のルーティング
  namespace :admin do # namespace do〜endで、adminルーティングの配下にusersルーティング設定
    resources :users, only: [:index, :destroy]
  end

  
  devise_for :users
  root to: 'homes#top'
  resources :games, only: [:new, :create, :index, :show, :destroy] do
    resource :favorites, only: [:create, :destroy] # いいね機能のルーティング、showページ不要でidの受け渡しも必要ないので単数系resource
    resources :post_comments, only: [:create, :destroy] # 投稿に対してコメントされるためpost_commentsは、gamesにネストする
  end
  resources :users, only: [:show, :edit, :update, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :game
  
end

app/models/game.rb
class Game < ApplicationRecord
  
  acts_as_taggable
  # acts_as_taggable_on :tags と同じ意味のエイリアス
  # tags のなかにIDやら名前などが入る。イメージ的には親情報。
  # tags のカラムを追加できる
  
  belongs_to :user
  attachment :image
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :game_title, presence: true, length: {minimum: 2}
  validates :impressions, presence: true

  def favorited_by?(user) # 引数で渡されたユーザidがFavoritesテーブル内に存在（exists?）するかどうかを調べるメソッドを定義
    favorites.where(user_id: user.id).exists? # モデル名.where(任意のカラム名: 格納されている値) user_idカラムの全レコードを検索し、user.idが含まれているか確認
  end
  
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :game
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :games, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :if_not_admin
  before_action :set_user, only: [:index, :destroy]

  def index
  end

  private
  
  def if_not_admin # 管理者以外でアクションを実行する場合は、ルートにリダイレクト
    redirect_to root_path unless current_user.admin?
  end
  
  def set_user # アクションで使用する変数をセット
    @users = User.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    games_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    game = Game.find(params[:game_id]) # パラメータ(game_id)で指定された投稿(gameテーブル)を検索して、変数に格納
    favorite = current_user.favorites.new(game_id: game.id) # favorite = Favorite.new(game_id: game.id) \ current_user_id = current_user.idと同じ
    # favorite = Favorite.new(game_id: game.id) # 上で取得した投稿IDをgame_idカラムに格納し、favoriteインスタンスに渡す
    # current_user_id = current_user.id # 『いいね』したユーザー（ログインユーザー）のIDを取得
    favorite.save
    redirect_to game_path(game) # 投稿詳細画面にリダイレクト
  end

  def destroy
    game = Game.find(params[:game_id])
    favorite = current_user.favorites.find_by(game_id: game.id) # 生成したfavoriteモデルのインスタンスのuser_idカラムにcurrent_user（ログインユーザー）を、game_idカラムに上で取得した投稿IDを格納
    favorite.destroy
    redirect_to game_path(game)
  end
  
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  
  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    @game.user_id = current_user.id
    if @game.save
      redirect_to games_path
    else
      render :new
    end
  end

  def index
    @games = Game.page(params[:page]).reverse_order # Kaminariのpageメソッドで決められた数のデータだけを取得する、.reverse_orderメソッド(現在のソート順を逆にする)で新着順に取得
    if params[:tag_name]
      @games = Game.tagged_with("#{params[:tag_name]}").page(params[:page]).reverse_order # tagged_with("タグ名")メソッド受け取ったtag_nameに値が入っている場合、タグ名で絞り込みを行う
      # タグ絞り込み＋page絞り込み
    end
  end
  
  def show
    @game = Game.find(params[:id])
    @post_comment = PostComment.new # コメント投稿用のインスタンス変数
    @post_comments = @game.post_comments.page(params[:page]).per(5) # コメントを全て取得=>コメントを5件取得
  end
  
  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    redirect_to games_path
  end
  
  private

  def game_params
    params.require(:game).permit(:game_title, :image, :impressions, :rate, :tag_list) # 星評価のrateカラム, タグ機能のtag_list
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
  
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  
  def create
    game = Game.find(params[:game_id]) # パラメータ(game_id)で指定された投稿を検索して、変数に格納
    comment = current_user.post_comments.new(post_comment_params) # comment = PostComment.new(post_comment_params) \ comment.user_id = current.user.idと同じ -->
    # comment = PostComment.new(post_comment_params) # コメントを取得し、生成したcommentインスタンスに渡す
    # comment.user_id = current.user.id # コメントしたユーザー（ログインユーザー）のIDを取得
    comment.game_id = game.id # PostCommentモデルのgame_idカラムに、上のパラメータで渡された投稿ID(Gameモデルのidカラム)を渡す
    comment.save
    redirect_to game_path(game) # 投稿詳細画面にリダイレクト
  end
  
  def destroy
    PostComment.find_by(id: params[:id], game_id: params[:game_id]).destroy # パラメータ(id,game_id)で指定されたコメントと投稿を検索して削除(URLにidが2つ)
    redirect_to game_path(params[:game_id])
  end
  
  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    @games = @user.games.page(params[:page]).reverse_order #@userに関連付けられた投稿（.game）のみ@gamesに渡す
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def index
    @users = User.all
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <div class="row no-gutters">
      <div class="profile-container card col-lg-10 m-auto">
        <div class="card-header bg-dark text-center">
          <h5 class="text-light">User Page</h5>
        </div>
        <% @users.each do |user| %>
        <div class="card-body w-100 text-center">
          <p>User image</p>
          <div class="card-img-top">
            <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %>
          </div>
          
          <%= link_to user_path(user.id), style: "text-decoration: none;" do %>
            <h6 class="card-title"><%= user.name %></h6>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/games/_tag_list.erb
<div class="tag-group">
  <p>タグ一覧</p>
  <% tag_list.each do |tag| %> <!-- gameブロック内のtag_listカラムからeachで、タグを配列から一つずつ取り出す -->
    <span class="badge badge-primary mr-1 p-2"><!-- badgeはラベル -->
      <%= link_to tag, games_path(tag_name: tag), class: "text-white" %><!-- タグを表示、tagのタグ名をパラメータとしてtag_nameメソッドで -->
    </span>
  <% end %>
</div>

app/views/games/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="text-center pt-5">
    <div class="container">
      <div class="row no-gutters">
        <div class="left-contents col-lg-7">
          <% @games.each do |game| %>
          <section class="card mb-5">
            <%= link_to game_path(game.id), style: "text-decoration: none;" do %>
              <h6 class="card-title bg-dark text-light py-3">ゲームタイトル：<%= game.game_title %></h6>
              <%= attachment_image_tag game, :image, class: "card-img-top shadow-lg" %>
            <% end %>
            <div class="card-body">
              <div class="row">
                <div class="col-2">
                  <p><%= attachment_image_tag game.user, :profile_image, fallback: "no_image.jpg", size: "60x60", class: "rounded-circle" %></br>
                  <%= game.user.name %></p>
                </div>
                <div class="col-10">
                  <p class="text-left p-3 shadow-lg"><%= game.impressions.truncate(100, omission: '...') %></p><!-- 100文字を超過したら...を表示する -->
                </div>
              </div>
            </div>
            <!-- タグ -->
            <%= render 'games/tag_list', tag_list: game.tag_list %>
            
            <!-- 星評価 -->
            <p>評価：<%= game.rate %>点</p>
            <!--星の数-->
            <div id="star-rate-<%= game.id %>"></div>
            <script>
            $('#star-rate-<%= game.id %>').raty({
              size: 36,
              starOff:  '<%= asset_path('star-off.png') %>',
              starOn : '<%= asset_path('star-on.png') %>',
              starHalf: '<%= asset_path('star-half.png') %>',
              half: true,
              readOnly: true,
              score: <%= game.rate %>,
            });
            </script>
            
            <p><%= link_to "#{game.post_comments.count} コメント", game_path(game.id) %></p> <!-- コメント件数の表示 -->
          </section>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div><%= paginate @games %></div>
</div>

app/views/games/show.html.erb
<div class="jumbotron jumbotron-fluid text-center">
  <div class="container">
    <div class="row no-gutters">
      <div class="col-lg-7 mr-auto my-5">
        <div class="game-body card">
          <h4 class="bg-dark text-light py-3">ゲームタイトル：<%= @game.game_title %></h4>
          <%= attachment_image_tag @game, :image,class: "card-img-top shadow-lg" %>
          <div class="card-body m-3">
            <p class="card-text">感想：<%= @game.impressions %></p>
            <div class="row">
              <div class="col-5 text-left">
                <p>投稿ユーザー：<%= @game.user.name %></p>
                <p>投稿日時：<%= @game.created_at.strftime('%Y/%m/%d') %></p> <!-- created_atカラム：ActiceRecordが自動的にデータを作成した日時を記録する -->
              </div>
              <div class="col-5 offset-md-2">
                <% if @game.user == current_user %>
                  <p class="bg-danger text-center p-1 rounded"><%= link_to "投稿を削除", game_path(@game), method: :delete, class: "text-light", style: "text-decoration: none;" %></p>
                <% end %>
                <!-- 『いいね』機能 -->
                <% if @game.favorited_by?(current_user) %> <!-- 投稿に付けられた『いいね』に自分（ログインユーザー）が含まれているか -->
                  <p> <!-- 含まれている場合 -->
                    <%= link_to game_favorites_path(@game), method: :delete do %> <!-- 『いいね』削除,ルーティングにgame_idが必要だから@game -->
                      ♥<%= @game.favorites.count %> いいね
                    <% end %>
                  </p>
                  <% else %>
                  <p> <!-- 含まれていない場合 -->
                    <%= link_to game_favorites_path(@game), method: :post do %> <!-- 『いいね』追加 -->
                      ♡<%= @game.favorites.count %> いいね
                    <% end %>
                  </p>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      
      <div class="col-lg-4 offset-md-1 shadow-lg my-5 border text-light">
        <div class="comments">
          <h4 class="bg-dark text-light py-3">コメント：5件まで表示</h4>
          <p class="text-light">コメント件数：<%= @game.post_comments.count %></p>
          <% @post_comments.each do |post_comment| %><!-- コントローラで@game.post_commentsを@post_commentsを定義したことで、@game.post_commentsしなくてもよくなった -->
            <div class="row m-2 p-2 border">
              <div class="col-4">
                <p><%= attachment_image_tag post_comment.user, :profile_image, fallback: "no_image.jpg", size: "40x40", class: "rounded-circle" %><br>
                <%= post_comment.user.name %></p> <!-- 画像を保持しているのはpost_commentモデルに紐づけられたuserモデル -->
                <small>
                  <div><%= post_comment.created_at.strftime('%Y/%m/%d') %></div>
                  <% if post_comment.user == current_user %>
                    <div class="comment-delete">
                      <%= link_to "削除する", game_post_comment_path(post_comment.game, post_comment), method: :delete, class: "text-danger", style: "text-decoration: none;"%> <!-- post_commentに結びついたgameとpost_commentの2つを用意 -->
                    </div>
                  <% end %>
                </small>
              </div>
              <div class="col-8">
                <small class="text-left"><%= post_comment.comment %></small>
              </div>
            </div>
          <% end %>
          <p><%= paginate @post_comments %></p>
          
          <div class="new-comment m-3">
            <%= form_with(model:[@game, @post_comment], local: true) do |f| %>
              <%= f.text_area :comment, rows:'5',placeholder: "コメント入力", class: "form-control mb-1" %>
              <%= f.submit "コメントを送信する", class: "btn btn-block btn-info" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="jumbotron jumbotron-fluid text-center"><!-- トップ見出しのデザイン,containerの外側に置くことで全幅,jumbotron-fluidで角の丸みを消す -->
  <div class="container text-light">
    <h1>Introduce each other to the GAME</h1>
    <p>面白かったゲームを皆に紹介しよう！</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="bg-dark">
      <nav class="navbar navbar-expand-lg navbar-light"><!-- ブレークポイントで切替表示,テキスト明るめ -->
        <div class="container">
          <!-- ブランドロゴ -->
          <a class="navbar-brand text-light p-1" href="/" alt="ロゴ"><%= image_tag 'controller-1784573_960_720.webp', :size =>'60x50' %>
          <h3 class="d-inline-block p-3">Introduce each other to the <strong>GAME</h3></strong>.</a>
          <button class="navbar-toggler" type="button" data-tpggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation"><!-- ハンバーガーメニューの枠 -->
            <span class="navbar-toggler-icon"></span><!-- ハンバーガーメニューの三本線 -->
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <!-- ナビゲーションアイコン内のメニュー -->
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to '投稿一覧', games_path, class: "nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to '投稿フォーム', new_game_path, class: "nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to 'マイページ', user_path(current_user.id), class: "nav-link text-light" %>
              </li>
              <% else %>
              <li class="nav-item">
                <%= link_to "新規登録", new_user_registration_path, class: "nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログイン", new_user_session_path, class: "nav-link text-light" %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer class="bg-dark", id="footer">
      <div class="container">
        <div class="row">
          <div class="mx-auto">
            <p class="text-light mt-3">© Introduce each other to the GAME</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="jumbotron jumbotron-fluid text-center", id="jumbotron-form">
  <div class="container">
    <div class="row no-gutters">
      <div class="col-lg-5 shadow-lg mx-auto my-5">
        <h4 class="bg-dark text-light py-3">プロフィール編集</h4>
        <p class="text-light">プロフィール情報を変更する</p>
        <div class="form-body p-5 text-light">
          <%= form_with model:@user, local:true do |f| %>
            <div class="form-group">
              <%= f.text_field :name, autofocus: true, placeholder: "ユーザー名", class: "form-control bg-transparent text-light", id: "user_name" %>
            </div>
            
            <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", size: "60x60", class: "rounded-circle" %>
            
            <div class="form-group mt-3">
              <label for="game_image">ユーザーイメージ</label><%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
            </div>
            
            <div class="actions mb-3">
              <%= f.submit "変更を保存", class: "btn btn-primary btn-info mt-4" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <div class="row no-gutters">
      <div class="profile-container card col-lg-10 m-auto">
        <div class="card-header bg-dark text-center">
          <h5 class="text-light">My Page</h5>
        </div>
        <div class="card-body w-100 text-center">
          <p>My image</p>
          <div class="card-img-top">
            <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %>
          </div>
          <h6 class="card-title"><%= @user.name %></h6>
        </div>
        <div class="card-footer text-center">
          <% if @user.id == current_user.id %>
            <p class="text-light"><%= link_to "プロフィール編集", edit_user_path(@user) %></p>
          <% end %>
        </div>
      </div>
      
      <div class="game-container col-lg-10 m-auto">
        <div class="card">
          <% @games.each do |game| %>
          <div class="card-body">
            <div class="card-img-top w-100">
            <%= link_to game_path(game.id) do %>
              <%= attachment_image_tag game, :image, class: "card-img-top"%>
            <% end %>
            </div>
          </div>
        </div>
      </div>
          <p>タイトル：<%= game.game_title %></p>
          <p>感想：<%= game.impressions %></p>
          <p>ユーザーネーム：<%= game.user.name %></p>
          <p><%= link_to "#{game.post_comments.count} コメント", game_path(game.id) %></p> <!-- コメント件数の表示 -->
        </div>
        <% end %>
        <%= paginate @games %>
      </div>
    </div>
  </div>
</div>